config/routes.rb
Rails.application.routes.draw do
  
  resources :submissions
  resources :subscribers, only: [:new, :create]
  resources :industries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
    resources :users, :has_many => :submissions
  end
  resources :industries , only: [:show, :create, :edit, :update] do
    resources :categories do
      resources :startups, module: :categories  
    end 
  end

  get "home" => "application#home"
  get "about" => "application#about"

  
  root 'subscribers#new'
 

end

app/models/industry.rb
class Industry < ActiveRecord::Base
	belongs_to :user
	has_many :categories

	searchkick text_start: [:name]
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: [:show, :edit, :update, :destroy]

  def index
    @industries = Industry.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 20)
    authorize @industries
  end

  def show
  	@categories = @industry.categories
  end

  def new
    @industry = Industry.new
    authorize @industry
  end

 
  def edit
  end


  def create
    @industry = Industry.new(industry_params)
    authorize @industry
    @industry.user = current_user
    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @industry.destroy
    respond_to do |format|
      format.html { redirect_to industries_url, notice: 'Industry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_industry
      @industry = Industry.find(params[:id])
      authorize @industry
    end
   # def correct_user
     # @industry = current_user.industries.find_by(id: params[:id])
      #redirect_to industries_path, notice: "Not authorized to edit this Industry" if @industry.nil?
   # end

    def industry_params
      params.require(:industry).permit(:name)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_demo.html.erb
<h2>How it works.</h2>
<div class="row">
	<div class="col-lg-12">
		<h3>1. Tell us what industry you'd like us to search.</h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<h3>2. Then tell us a little bit about your business.</h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<h3>3. We do all the searching on google and paid databases, </h3>
			<h3> build the report, and send it right to your inbox.</h3>
	</div>
</div>
	 
	 
   
		
         

   

app/views/industries/_form.html.erb
<%= form_for(@industry) do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/industries/_sample.html.erb
<h3 class="text-center">Check out our sample report.</h3>
<br>
<h4 class="text-center">We built this report for a startup in the Outdoor industry looking for businesses that help customers hire an outdoor guide.</h4>
<br>
<h4><strong>Number of startups:</strong> 8</h4>
<br>
	<h4><strong> Name:</strong> Guidehire</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/guidehire">https://angel.co/guidehire</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>GuideHire is the online marketplace that connects consumers with a network of outdoor guides and instructors. If it gets you outside, We Know A Guide.<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> Charter smarter</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/charter-smarter">https://angel.co/charter-smarter</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>SplitTrips.com is a web and mobile application that provides an online marketplace for Charter Fishing and Hunting Lodge providers to sell their unfilled charter slots and State issued game tags online, last minute.<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> Fin and Field</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/fin-field">https://angel.co/fin-field</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>A Hunting and Fishing Marketplace<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> Vestigo Adventures</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/vestigo-adventures">https://angel.co/vestigo-adventures</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>Guided outdoor adventures from local professionals<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> TRAIL.PL </h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/trail-pl-trails-maps-and-gps">https://angel.co/trail-pl-trails-maps-and-gps</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>Easy way to connect outdoor/gps enthusiast with guides, instructors and accomodation.<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> Fishing Guides 360</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/fishing-guides-360">https://angel.co/fishing-guides-360</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>Fishing Guides 360 is a multi-sided SaaS for fishing guides and charter boats. We integrate the booking and reservation management system with a retail booking engine and a suite of marketing tools. This enables guides and captains to spend more time fishing and less time managing and marketing their business. 

The booking engine enables anglers to search for guides, charter boats, and available spots and securely book online. 

FG360 is one member of the Outdoor Guides 360 family of products.<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> FishingBooker</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/fishingbooker">https://angel.co/fishingbooker</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>World's largest online marketplace for fishing charters.<p>

			<br> 
			<hr>
	<h4><strong> Name:</strong> Switchback Travel</h4>
	<h4><strong>More Info:</strong> <a href="https://angel.co/switchback-travel-1">https://angel.co/switchback-travel-1</a></h4>
	<h4><strong> Description:</strong> <h4>
		<p>Switchback Travel is building the world’s premier adventure travel information brand. We provide adventure travel guides and lifestyle with destinations in the United States, Europe, South America, Asia, and more. Revenue is advertisement-based, with the travel and outdoor sectors commanding some of the highest rates on the market. Switchback Travel was meticulously designed and built by top Seattle firms (Design Hovie Studios and the Bear Group) for a high revenue and targeted audience.<p>
		
		<hr>
		<br>

app/views/industries/edit.html.erb
<div class="container">
	<div class="box">
		<h1>Edit industry</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @industry %> |
		<%= link_to 'Back', industries_path %>
	</div>
</div>

app/views/industries/index.html.erb
<div class="container">
 <% if policy(Industry).new? %>
  <div class="jumbotron">
    <h1>Looking for a startup's competition?</h1>
    <h4>We'll do the research for you!</h4>
    



     <% if policy(Industry).new? %>
      <% else %>
       <a href="mailto:alex@kehaya.com">Want to add your industry? Contact me for access.</a>
      <% end %>


 
    <table class="table table-striped">
        <thead>
          <th></th>
          <th></th>
        </thead>

        <tbody>
          <% @industries.each do |industry| %>
          <tr>
            <td>
              <ul>
                <ol><strong>Industry:</strong> <%= industry.name %></ol>
                <ol><strong>Categories:</strong> <%= industry.categories.count %></ol> 
                <ol><strong>Owner:</strong> <%= industry.user.name if industry.user %></ol>
              </ul>
            </td> 

            <td>
            <%= link_to 'View', industry, class: "btn btn-xs btn-success" if policy(industry).show? %>
            <% if industry.user === current_user %>
            <%= link_to 'Edit', edit_industry_path(industry), class: "btn btn-xs btn-primary" if policy(industry).update? %></a>
            <%= link_to 'Delete', industry, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger"  if policy(industry).destroy? %>
            </td>
            <% end %>
          </tr>
              
          <% end %>
       </tbody>
     </thead>
   </table>

    <br>


    <% if user_signed_in? %>
     
      <%= link_to 'New Industry', new_industry_path, class: "btn btn-primary" %>
      <% else %>
       <a href="mailto:alex@kehaya.com">Want to add your industry? Contact me for access.</a>
       <% end%>

    <% else %>
      <h1> You don't have access to this page</h1>
    <% end %>  
  </div>
</div>

app/views/industries/new.html.erb
<div class="container">
	<div class="box">
		<h1>New industry</h1>

		<%= render 'form' %>

		<%= link_to 'Back', industries_path %>
	</div>
</div>

app/views/industries/show.html.erb
<div class="container">
	<div class="box">

		<h3>Here's a report we did for guide hiring company in the Outdoor industry.</h3>
		<h3></h3>
		<p>
		  <%= render "categories/index" , :categories => @categories %>
		</p>

		<%= link_to 'Edit', edit_industry_path(@industry) %> |
		<%= link_to 'Back', industries_path %>
	</div>
</div>