config/routes.rb
Rails.application.routes.draw do
  
  resources :submissions
  resources :subscribers, only: [:new, :create]
  resources :industries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
    resources :users, :has_many => :submissions
  end
  resources :industries , only: [:show, :create, :edit, :update] do
    resources :categories do
      resources :startups, module: :categories  
    end 
  end

  get "home" => "application#home"
  get "about" => "application#about"

  
  root 'subscribers#new'
 

end

app/models/submission.rb
class Submission < ActiveRecord::Base
	belongs_to :user
end

app/controllers/submissions_controller.rb
class SubmissionsController < InheritedResources::Base
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def index
    @submissions = Submission.all
    authorize @submissions
  end

  def show
  end

  def new
    @submission = Submission.new
    authorize @submission
  end

 
  def edit
  end


  def create
    @submission = Submission.new(submission_params)
    authorize @submission
    @submission.user = current_user
    respond_to do |format|
      if @submission.save
        format.html { redirect_to root_path, notice: 'Submission was successfully created. Our team is working on your report and will have it to you soon.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_submission
      @submission = Submission.find(params[:id])
      authorize @submission
    end

    def submission_params
      params.require(:submission).permit(:url, :name, :business, :description, :user_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :business, "Industry" %><br>
    <%= f.text_field :business, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.url_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<div class="container">
	<div class="box">
		<h1>Editing submission</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @submission %> |
		<%= link_to 'Back', root_path %>
	</div>
</div>

app/views/submissions/index.html.erb
<div class="container">
  <div class="box">
    <h1>Listing submissions</h1>
        <% @submissions.each do |submission| %>
          <div class="submission">
            <h3><strong>User Name:</strong> <%= submission.user.name %></h3>
            <h3><strong>User Email:</strong> <%= submission.user.email %></h3>
            <h3><strong>Description:</strong> <%= submission.description %></h3>
            <h3><strong>Industry:</strong> <%= submission.name %></h3>
            <h3><strong>URL:</strong> <%= link_to submission.url, submission.url %></h3>
            <h3><%= submission.business %></h3>
            <%= link_to 'Show', submission %>
            <%= link_to 'Edit', edit_submission_path(submission) %>
            <%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

        <% end %>
    <br>

    <%= link_to 'New Submission', new_submission_path %>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="container">
	<div class="box">
		<h1>New submission</h1>

		<%= render 'form' %>

		<%= link_to 'Back', root_path %>
	</div>
</div>

app/views/submissions/show.html.erb
<div class="container">
	<div class="box">

		<p>
		  <strong>User:</strong>
		  <%= @submission.user.name %>
		  <%= @submission.user.email %>
		</p>
		<p>
		  <strong>Industry:</strong>
		  <%= @submission.business %>
		</p>
		<p>
		  <strong>Business Name:</strong>
		  <%= @submission.name %>
		</p>
		<p>
		  <strong>Business URL:</strong>
		  <%= link_to @submission.url, @submission.url %>
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @submission.description %>
		</p>
		

		<%= link_to 'Edit', edit_submission_path(@submission) %> |
		<%= link_to 'Back', root_path %>
	</div>
</div>