config/routes.rb
Rails.application.routes.draw do
  
  resources :submissions
  resources :subscribers, only: [:new, :create]
  resources :industries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users do
    resources :users, :has_many => :submissions
  end
  resources :industries , only: [:show, :create, :edit, :update] do
    resources :categories do
      resources :startups, module: :categories  
    end 
  end

  get "home" => "application#home"
  get "about" => "application#about"

  
  root 'subscribers#new'
 

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :startups, as: :startupable
	belongs_to :industry
	belongs_to :user
end

app/controllers/categories/startups_controller.rb
class Categories::StartupsController < StartupsController
before_action :set_startupable
	def show
	end

	def create
		@startup = @startupable.startups.new startup_params
		@startup.user = current_user
		@startup.save
		redirect_to industry_category_path(id: @startupable.id)
		authorize @startup
	end

	private

	def set_startupable
		@startupable = Category.find(params[:category_id])
		authorize @startupable
	end

	def set_startup
		@startup = Startup.find(params[:id])
		authorize @startup
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @categories = Category.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
    authorize @categories
  end

  def show
  end


  def new
    @industry = Industry.find(params[:industry_id])
    @category = @industry.categories.new
    authorize @category
  end

 
  def edit
  end


  def create
    @industry = Industry.find(params[:industry_id])
    @category = @industry.categories.new(category_params)
    @category.save
    respond_with @industry
    authorize @category
  end


  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @industry, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @category.destroy
    redirect_to @industry
    flash[:notice] = "You have succesfully deleted the category."
  end

  private
    def set_category
      @category = Category.find(params[:id])
      @industry = Industry.find(params[:industry_id])
      authorize @category
    end
    def correct_user
      @category = current_user.categories.find_by(id: params[:id])
      redirect_to categories_path, notice: "Not authorized to edit this Category" if @category.nil?
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for([@industry, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/_index.html.erb
<% @categories.each do |category| %>
  
    <h4><%= category.name %></h4>
    <h4>Number of startups found: <%= category.startups.count %></h4>
    
    <%= link_to 'View Report', [category.industry, category], class: "btn btn-lg btn-success" if policy(category).show? %>
      <% if user_signed_in? %>
      
    <%= link_to 'Edit', edit_industry_category_path(category.industry, category), class: "btn btn-xs btn-primary" if policy(category).update? %>
  
    
    <%= link_to 'Delete', [category.industry, category], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" if policy(category).destroy?  %>
 
  <% end %>
<% end %>
    <br>

    <% if user_signed_in? %>
      <% if policy(Category).new? %>
      <%= link_to 'New Category', new_industry_category_path(@industry), class: "btn btn-primary" %>
      <% else %>

      <a href="mailto:alex@kehaya.com">Want to add your category? Contact me for access.</a>
      <% end %>

    <% else %>
    <% end %>  
    

app/views/categories/edit.html.erb
<div class="container">
	<div class="box">
		<h1>Edit category</h1>

		<%= render 'form' %>

		<%= link_to 'Show', [@industry, @category] %> |
		<%= link_to 'Back', @industry %>

	</div>
</div>

app/views/categories/index.html.erb
<% if policy(Category).user? %>
<div class="panel panel-default">
    <div class="panel-heading">
      <h1>Outdoor Startup Categories</h1>
  </div>
    <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Number of startups</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td><%= category.startups.count %></td>
                
                <td><%= link_to 'View', category, class: "btn btn-default" if policy(category).show? %>
                  <% if user_signed_in? %>
                  
                <%= link_to 'Edit', edit_category_path(category), class: "btn btn-default" if policy(category).update? %>
              
                
                <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" if policy(category).destroy?  %></td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <div class="center">
          <%= will_paginate @categories, renderer: BootstrapPagination::Rails %>
        </div>
      </div>

    <br>


  <div class="panel-footer">
    <% if user_signed_in? %>
      <%= link_to 'New Category', new_category_path, class: "btn btn-primary" if policy(Category).new? %>
        <% else %>
      <%= link_to "Sign up to add your own category", new_user_registration_path %>
    <% end %>  
  </div>
</div>
<% else %>
  <%= render "landing" %>
<% end %>

app/views/categories/new.html.erb
<div class="container">
    <div class="box">
		<h1>New category</h1>

			<%= render 'form' %>

		<%= link_to 'Back', @industry, class: "btn btn-primary" %>

	</div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="box">
			<h3><%= @category.name %></h3>
			<h4>Number of startups: <%= @category.startups.count %></h4>

		<%= render partial: "startups/startups", locals: {startupable: @category} %>



		<% if policy(@category).update? %>
		<%= link_to 'Edit', edit_industry_category_path(@category.industry, @category)  %> | <%= link_to 'Back', @category.industry %>
		
		<% end %>
	</div>

	<br>

		<% if user_signed_in? %>
			<%= render partial: "startups/form", locals: {startupable: @category} %>
		<% end %>
</div>